/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesAuditRootCauseAnalysisRouteImport } from './routes/services_.audit-root-cause-analysis'
import { Route as ServicesCivilStructuralEngineeringRouteImport } from './routes/services_.civil-structural-engineering'
import { Route as ServicesDesignDocumentationRouteImport } from './routes/services_.design-documentation'
import { Route as ServicesElectricalEngineeringRouteImport } from './routes/services_.electrical-engineering'
import { Route as ServicesMechanicalEngineeringRouteImport } from './routes/services_.mechanical-engineering'
import { Route as ServicesProjectSupportRouteImport } from './routes/services_.project-support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAuditRootCauseAnalysisRoute =
  ServicesAuditRootCauseAnalysisRouteImport.update({
    id: '/services_/audit-root-cause-analysis',
    path: '/services/audit-root-cause-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCivilStructuralEngineeringRoute =
  ServicesCivilStructuralEngineeringRouteImport.update({
    id: '/services_/civil-structural-engineering',
    path: '/services/civil-structural-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDesignDocumentationRoute =
  ServicesDesignDocumentationRouteImport.update({
    id: '/services_/design-documentation',
    path: '/services/design-documentation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesElectricalEngineeringRoute =
  ServicesElectricalEngineeringRouteImport.update({
    id: '/services_/electrical-engineering',
    path: '/services/electrical-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMechanicalEngineeringRoute =
  ServicesMechanicalEngineeringRouteImport.update({
    id: '/services_/mechanical-engineering',
    path: '/services/mechanical-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesProjectSupportRoute = ServicesProjectSupportRouteImport.update({
  id: '/services_/project-support',
  path: '/services/project-support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/audit-root-cause-analysis': typeof ServicesAuditRootCauseAnalysisRoute
  '/services/civil-structural-engineering': typeof ServicesCivilStructuralEngineeringRoute
  '/services/design-documentation': typeof ServicesDesignDocumentationRoute
  '/services/electrical-engineering': typeof ServicesElectricalEngineeringRoute
  '/services/mechanical-engineering': typeof ServicesMechanicalEngineeringRoute
  '/services/project-support': typeof ServicesProjectSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/audit-root-cause-analysis': typeof ServicesAuditRootCauseAnalysisRoute
  '/services/civil-structural-engineering': typeof ServicesCivilStructuralEngineeringRoute
  '/services/design-documentation': typeof ServicesDesignDocumentationRoute
  '/services/electrical-engineering': typeof ServicesElectricalEngineeringRoute
  '/services/mechanical-engineering': typeof ServicesMechanicalEngineeringRoute
  '/services/project-support': typeof ServicesProjectSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services_/audit-root-cause-analysis': typeof ServicesAuditRootCauseAnalysisRoute
  '/services_/civil-structural-engineering': typeof ServicesCivilStructuralEngineeringRoute
  '/services_/design-documentation': typeof ServicesDesignDocumentationRoute
  '/services_/electrical-engineering': typeof ServicesElectricalEngineeringRoute
  '/services_/mechanical-engineering': typeof ServicesMechanicalEngineeringRoute
  '/services_/project-support': typeof ServicesProjectSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sectors'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services/audit-root-cause-analysis'
    | '/services/civil-structural-engineering'
    | '/services/design-documentation'
    | '/services/electrical-engineering'
    | '/services/mechanical-engineering'
    | '/services/project-support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sectors'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services/audit-root-cause-analysis'
    | '/services/civil-structural-engineering'
    | '/services/design-documentation'
    | '/services/electrical-engineering'
    | '/services/mechanical-engineering'
    | '/services/project-support'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sectors'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services_/audit-root-cause-analysis'
    | '/services_/civil-structural-engineering'
    | '/services_/design-documentation'
    | '/services_/electrical-engineering'
    | '/services_/mechanical-engineering'
    | '/services_/project-support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SectorsRoute: typeof SectorsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ServicesAuditRootCauseAnalysisRoute: typeof ServicesAuditRootCauseAnalysisRoute
  ServicesCivilStructuralEngineeringRoute: typeof ServicesCivilStructuralEngineeringRoute
  ServicesDesignDocumentationRoute: typeof ServicesDesignDocumentationRoute
  ServicesElectricalEngineeringRoute: typeof ServicesElectricalEngineeringRoute
  ServicesMechanicalEngineeringRoute: typeof ServicesMechanicalEngineeringRoute
  ServicesProjectSupportRoute: typeof ServicesProjectSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/audit-root-cause-analysis': {
      id: '/services_/audit-root-cause-analysis'
      path: '/services/audit-root-cause-analysis'
      fullPath: '/services/audit-root-cause-analysis'
      preLoaderRoute: typeof ServicesAuditRootCauseAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/civil-structural-engineering': {
      id: '/services_/civil-structural-engineering'
      path: '/services/civil-structural-engineering'
      fullPath: '/services/civil-structural-engineering'
      preLoaderRoute: typeof ServicesCivilStructuralEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/design-documentation': {
      id: '/services_/design-documentation'
      path: '/services/design-documentation'
      fullPath: '/services/design-documentation'
      preLoaderRoute: typeof ServicesDesignDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/electrical-engineering': {
      id: '/services_/electrical-engineering'
      path: '/services/electrical-engineering'
      fullPath: '/services/electrical-engineering'
      preLoaderRoute: typeof ServicesElectricalEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/mechanical-engineering': {
      id: '/services_/mechanical-engineering'
      path: '/services/mechanical-engineering'
      fullPath: '/services/mechanical-engineering'
      preLoaderRoute: typeof ServicesMechanicalEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/project-support': {
      id: '/services_/project-support'
      path: '/services/project-support'
      fullPath: '/services/project-support'
      preLoaderRoute: typeof ServicesProjectSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SectorsRoute: SectorsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ServicesAuditRootCauseAnalysisRoute: ServicesAuditRootCauseAnalysisRoute,
  ServicesCivilStructuralEngineeringRoute:
    ServicesCivilStructuralEngineeringRoute,
  ServicesDesignDocumentationRoute: ServicesDesignDocumentationRoute,
  ServicesElectricalEngineeringRoute: ServicesElectricalEngineeringRoute,
  ServicesMechanicalEngineeringRoute: ServicesMechanicalEngineeringRoute,
  ServicesProjectSupportRoute: ServicesProjectSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
