import { createFileRoute } from '@tanstack/react-router'
import { ContactBay, PageHero, SectionLead, pageHead } from '../components/Site'
import { values } from '../content/site'
export const Route = createFileRoute('/about')({ head: () => pageHead('About', 'Meet YUKTI Engineering & Projects, an engineering-led consulting and project support partner focused on practical, responsible solutions.'), component: About })
function About(){ return <main id="main"><PageHero image="/assets/yukti-engineering-hero.webp" imageAlt="Integrated electrical, structural and mechanical engineering infrastructure" index="01" title="Engineering judgement that respects the real world." intro="YUKTI Engineering & Projects is an engineering-led consulting and project support partner focused on practical, technically sound and value-conscious solutions." />
<section className="about-intro page-section"><div><SectionLead index="A" label="Our commitment" title="Solve what matters. Intervene where it counts." /></div><div className="prose"><p>We integrate engineering analysis, design review, troubleshooting, technical audits and execution support to help clients make confident decisions.</p><p>Every recommendation is considered against safety, reliability, performance, future readiness and investment. We work to avoid unnecessary replacement, overdesign and capital expenditure that does not address the underlying need.</p></div></section>
<section className="vision-grid page-section"><article><span>VISION</span><h2>To be a trusted engineering and projects partner.</h2><p>Known for technical depth, practical judgement and responsible engineering.</p></article><article><span>MISSION</span><h2>To turn complexity into implementable solutions.</h2><p>Protecting people, assets, uptime and investment through clear engineering.</p></article></section>
<section className="values-section page-section"><SectionLead index="B" label="Values" title="The standards behind every decision." /><div className="values-grid">{values.map(([t,p],i)=><article key={t}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
<section className="philosophy"><p>UNDERSTAND THE PROBLEM.</p><p>ENGINEER THE SOLUTION.</p><p>DELIVER THE VALUE.</p></section><ContactBay /></main> }
